### ISSUE TITLE
#include "curses" issue

### ISSUE THREAD

**Issue by ghost** [goldblattster/hex-editor#1]
In main.h, #include "curses" just.. don't work, or should the makefile added with linking options?

**Comment by ddpanasyuk** [comment]
You need to have the curses library, or some compatible variation of it,
installed on your system. Link it and it should compile.

BTW, this program was never really completed, and as such it only dumps hex
for you to read address by address; there's no hex write capabilities as
far as I can remember.

**Comment by ghost** [comment]
Then, the real issue is in the makefile? I'm expecting an executable after running _make_.

Update - Oh, I found that I forgot to install libncurses5. Now I'm trying to compile it.

**Comment by ghost** [comment]
After installing, and running make. It worked.

Issue solved. The delimiter really confusing me :(.  I think I it will generate a file named _ncurses.h_ when I run **_make**_
